let fs = require("fs");
let express = require("express");
let cors = require("cors");

let port = process.env.PORT || 6327;

let app = express();

//this is required to allow for fetch() to work. It does not follow web safety
//  standards, but this was the simplest solution considering our URLs are not
//  set (can be flip1, flip2, etc.)
app.use(cors({
  origin: '*'
}));

app.use(express.json());
app.use(express.static("static"));
app.set("view engine", "ejs");

/*
 * gets object with the most recent copy of the message history
 * Returns {obj} - object with list of messages
 */
function getMessages(){
    return JSON.parse(fs.readFileSync(__dirname + "/message-history.json"));
}

/*
 * gets the number of messages stored server-side
 * Returns {int} - number of stored messages
 */
function getMessageCount(){
    const mssgs = getMessages();
    return mssgs.messages.length;
}

/*
 * GET home page
 */
app.get("/", function (req, res, next){
    console.log("== GET /");
    res.render("home");
});

/*
 * GET hider page
 */
app.get("/hider", function (req, res, next){
    console.log("== GET /hider");
    res.render("hider");
});

/*
 * GET chat page
 * Param: role - either "seeker" or "hider"
 */
app.get("/chat/:role", function (req, res, next){
    let role = req.params.role.toLowerCase();
    if(role != "seeker" && role != "hider"){
        next();
    }
    //capitalizes the first letter (ex. "hider" -> "Hider")
    role = role.charAt(0).toUpperCase() + role.substring(1, role.length);
    res.render("messaging", {role});
});

/*
 *******************************************************************************
 Sending & recieving messages
 *******************************************************************************
 */

/*
 * POST a new message
 * stores new messages on the server for everyone to access
 */
app.post("/new-message", function (req, res){
    console.log("== POST /new-message");
    let mssgs = getMessages();
    mssgs.messages.push(req.body);
    fs.writeFileSync(
        "./message-history.json",
        JSON.stringify(mssgs, null, 2)
    );
    res.status(200).send("Message Recieved.");
});

/*
 * GET the number of server-side messages
 * used to see if there's a discrepency between server and client (aka if a new
 *   message has been sent)
 */
app.get("/message-change", function (req, res, next){
    //console.log("== GET /message-change");
    let mssgNum = getMessageCount();
    //console.log("  -- count = " + mssgNum);
    res.status(200).json({count: mssgNum});
});

/*
 * GET messages
 * send all messages to client
 */
app.get("/messages", function (req, res, next){
    console.log("== GET /messages");
    res.status(200).sendFile(__dirname + "/message-history.json");
});

/*
 *******************************************************************************
 Drawing Cards
 *******************************************************************************
 */

// .cards so that we get the array inside the JSON object
var cards = JSON.parse(fs.readFileSync(__dirname + "/cards.json")).cards
var idx_of_cards_drawn = []
var num_of_cards = 0

function getRandomInt(min, max) {
  min = Math.ceil(min)
  max = Math.floor(max)
  return Math.floor(Math.random() * (max - min + 1)) + min
}

function isCardAlreadyDrawn(idx) {
    for (let i = 0; i < idx_of_cards_drawn.length; i++) {
        if(idx == idx_of_cards_drawn[i]){
            return true
        }
    }
    return false
}

/*
 * Drawing Cards
 */
app.get("/draw-card", (req, res) => {
    console.log("== GET /draw-card");

    // Generate a random index for the card
    var idx = getRandomInt(0, cards.length - 1)

    // If num of cards is 0, just add the card
    if(num_of_cards == 0) {
        idx_of_cards_drawn.push(idx)
    } else { // Else, check if card is already drawn
        while (isCardAlreadyDrawn(idx)) {
            idx = getRandomInt(0, cards.length - 1)
        }
        idx_of_cards_drawn.push(idx)
    }

    // Get the num of cards in hand
    num_of_cards = idx_of_cards_drawn.length
    console.log("idx length: " + idx_of_cards_drawn.length)
    console.log("Num of cards drawn: " + num_of_cards)
    console.log("Indices of cards drawn: " + idx_of_cards_drawn)

    // Render the card 
    res.render("cardDraw", {
        cards: cards,
        num_of_cards: num_of_cards,
        idx_of_cards_drawn: idx_of_cards_drawn
    }) 
});

app.get("*splat", function (req, res){
    console.log("== GET", req.originalUrl);
    console.log("   ~~ Error: 404");
    res.render("404");
});

app.listen(port, function (){
    console.log("== listening on " + port);
});

//clearing the message history upon server stop (when server stopped via Ctrl C)
//pulled from script generated by Copilot

process.on("SIGINT", () =>{
    console.log("\n\n\n~~ Interrupt Signal (^C) recieved");

    let emptyMessages = {
        messages: []
    };

    fs.writeFileSync(
        "./message-history.json", 
        JSON.stringify(emptyMessages, null, 2)
    );

    console.log("~~ ./message-history.json cleared.");
    process.exit();
});